from collections.abc import Callable, Sequence
from typing import Any, TypeAlias, TypeVar, overload

from django.apps.config import AppConfig
from django.core.checks.messages import CheckMessage

class Tags:
    admin: str = ...
    caches: str = ...
    compatibility: str = ...
    database: str = ...
    models: str = ...
    security: str = ...
    signals: str = ...
    templates: str = ...
    translation: str = ...
    urls: str = ...

_CheckCallable: TypeAlias = Callable[..., Sequence[CheckMessage]]
_C = TypeVar("_C", bound=_CheckCallable)

class CheckRegistry:
    registered_checks: set[Callable[..., Any]] = ...
    deployment_checks: set[Callable[..., Any]] = ...
    def __init__(self) -> None: ...
    @overload
    def register(self, check: _C, *tags: str, **kwargs: Any) -> _C: ...
    @overload
    def register(self, check: str | None = ..., *tags: str, **kwargs: Any) -> Callable[[_C], _C]: ...
    def run_checks(
        self,
        app_configs: list[AppConfig] | None = ...,
        tags: list[str] | None = ...,
        include_deployment_checks: bool = ...,
    ) -> list[CheckMessage]: ...
    def tag_exists(self, tag: str, include_deployment_checks: bool = ...) -> bool: ...
    def tags_available(self, deployment_checks: bool = ...) -> set[str]: ...
    def get_checks(self, include_deployment_checks: bool = ...) -> list[Callable[..., Any]]: ...

registry: CheckRegistry
register = registry.register
run_checks = registry.run_checks
tag_exists = registry.tag_exists
