from typing import Any

import django.contrib.admin as admin

class RedirectAdmin(admin.ModelAdmin[Any]):
    list_display: Any = ...
    list_filter: Any = ...
    search_fields: Any = ...
    radio_fields: Any = ...
