from typing import Any

import django.contrib.admin as admin

class FlatPageAdmin(admin.ModelAdmin[Any]):
    form: Any = ...
    fieldsets: Any = ...
    list_display: Any = ...
    list_filter: Any = ...
    search_fields: Any = ...
