#!/bin/bash

set -ex

# format code
if [[ $CI ]]; then
  ruff format --check tests django-stubs
  ruff check django-stubs
else
  ruff format tests django-stubs
  ruff check --fix --exit-non-zero-on-fix django-stubs
fi

# type check code
mypy tests django-stubs

# pyright tests
pyright tests django-stubs
pytest tests django-stubs -p no:warnings -v

# ty tests
ty check tests django-stubs
