#!/bin/bash

export PATH="$(pwd)/.venv/bin:$(pwd)/node_modules/.bin:$PATH"
set -ex

# format code
if [[ $CI ]]; then
  uv run black --check tests typings
  uv run isort --check-only tests typings
  uv run ruff check typings/*
else
  uv run black tests typings
  uv run isort tests typings
  uv run ruff check --fix --exit-non-zero-on-fix typings/*
fi

# type check code
uv run mypy tests typings

# pyright tests
pyright tests typings
uv run pytest tests typings -p no:warnings -v

# lint
uv run flake8 tests typings
